#!/bin/bash
#PBS -N myjob
#PBS -k oe
#PBS -m be
#

cd /data/takedatn/TUB_DIMER

NAMD_VER=2.9
NETWORK=ib
TRANS=ibverbs

PATH=/usr/local/NAMD/$NAMD_VER/$NETWORK/$TRANS:$PATH

cd $PBS_O_WORKDIR

# Create host file (required)
make-namd-nodelist
charmrun ++nodelist ~/namd.$PBS_JOBID ++p $np `which namd2` NPT_tubulin_36_2_restart_NUM2.conf > /data/username/TUB_DIMER/output2/NPT_NUM2.log
rm -f ~/namd.$PBS_JOBID
